name: Docker Image CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose up -d --build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run npm test
      run: |
        docker-compose exec -T app npm run test
  
