name: Run Tests

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test -- --testPathPattern="tests/domain"
      - name: Check test status
        run: |
          if [ $? -eq 0 ]; then
            echo "All tests passed"
          else
            echo "Tests failed"
            exit 1
          fi
  code-analysis:
    runs-on: ubuntu-latest
    needs: unit-test

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: web_cafeteria/app
          args: >
            -Dsonar.organization=arianemadureira
            -Dsonar.projectKey=arianemadureira_web_cafeteria
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=lib/
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
