name: Run Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Start Docker
        run: docker-compose up -d --build

      - name: Wait for web service to be ready
        run: |
          timeout=300
          while ! curl -s http://localhost:3000 > /dev/null; do
              timeout=$(($timeout - 1))
              if [ $timeout -eq 0 ]; then
                  echo "Service did not become ready in time"
                  exit 1
              fi
              sleep 1
          done
